name: Output Information with Activity Types
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo "${{ toJSON(github) }}"